
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author markl
 */
public class LoginGUIForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginGUIForm
     */
    public LoginGUIForm() {
        initComponents();
        
        jtbMain.setEnabledAt(1,false);
        // center the form
        this.setLocationRelativeTo(null);
        // change color of background
        this.getContentPane().setBackground(new Color(48, 213, 200));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbMain = new javax.swing.JTabbedPane();
        pnlLogin = new javax.swing.JPanel();
        lblECS = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        bttnLogin = new javax.swing.JButton();
        bttnRegister = new javax.swing.JButton();
        bttnExit = new javax.swing.JButton();
        pnlInformation = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GB Manufacturing");

        lblECS.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblECS.setText("Equipment Checkin/Checkout System");

        lblUser.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblUser.setText("Username:");

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/22f025440326410a000ee7366565ef42fbdb7eed.jpg"))); // NOI18N

        lblPass.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblPass.setText("Password:");

        txtUser.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserKeyReleased(evt);
            }
        });

        txtPass.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassKeyReleased(evt);
            }
        });

        bttnLogin.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bttnLogin.setText("Login");
        bttnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnLoginActionPerformed(evt);
            }
        });

        bttnRegister.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bttnRegister.setText("Register");
        bttnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnRegisterActionPerformed(evt);
            }
        });

        bttnExit.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        bttnExit.setText("Exit");
        bttnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlLoginLayout.createSequentialGroup()
                                        .addComponent(lblUser)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtUser))
                                    .addGroup(pnlLoginLayout.createSequentialGroup()
                                        .addComponent(lblPass)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPass)))
                                .addGap(18, 18, 18))
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addComponent(bttnLogin)
                                .addGap(18, 18, 18)
                                .addComponent(bttnRegister)
                                .addGap(18, 18, 18)
                                .addComponent(bttnExit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblECS))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(lblECS)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUser)
                            .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPass)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttnLogin)
                            .addComponent(bttnRegister)
                            .addComponent(bttnExit)))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jtbMain.addTab("Login", pnlLogin);

        javax.swing.GroupLayout pnlInformationLayout = new javax.swing.GroupLayout(pnlInformation);
        pnlInformation.setLayout(pnlInformationLayout);
        pnlInformationLayout.setHorizontalGroup(
            pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1319, Short.MAX_VALUE)
        );
        pnlInformationLayout.setVerticalGroup(
            pnlInformationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 639, Short.MAX_VALUE)
        );

        jtbMain.addTab("Information", pnlInformation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtbMain)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtbMain)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void bttnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnLoginActionPerformed
        try {
            // Login
            submitLogin();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(LoginGUIForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(LoginGUIForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bttnLoginActionPerformed

    private void bttnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bttnExitActionPerformed

    private void bttnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnRegisterActionPerformed
        // Go to User Registration Form:
        RegisterGUI rg = new RegisterGUI();
        rg.setVisible(true);
    }//GEN-LAST:event_bttnRegisterActionPerformed

    private void txtUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyReleased
        // Change background to red until valid
        validateInputs();
    }//GEN-LAST:event_txtUserKeyReleased

    private void txtPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyReleased
        // Change background to red until valid
        validateInputs();
    }//GEN-LAST:event_txtPassKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUIForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnExit;
    private javax.swing.JButton bttnLogin;
    private javax.swing.JButton bttnRegister;
    private javax.swing.JTabbedPane jtbMain;
    private javax.swing.JLabel lblECS;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlInformation;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
    private String validateInputs() {
        StringBuilder errors = new StringBuilder();
        
        String username = txtUser.getText();
        String password = txtPass.getText();

        // Check if emp_Username meets the criteria
        if (username.isBlank() || username.length() < 11) {
            errors.append("Please provide a valid username (at least 12 characters long).\n");
        }

        // Check if emp_Password meets the criteria
        if (password.isBlank() || password.length() < 11
                || !Pattern.compile("^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[!@#$%^&+=]).*$").matcher(password).matches()) {
            errors.append("Please provide a valid password (at least 12 characters long, containing at least one uppercase letter, one lowercase letter, one digit, and one special character).\n");
        }

        return errors.toString();
    }

    private void submitLogin() throws ClassNotFoundException, SQLException {
        String validationErrors = validateInputs();
        if (!validationErrors.isEmpty()) {
            // Display all error messages
            JOptionPane.showMessageDialog(this, "Invalid username/password:\n" + validationErrors);
            clear();
        }else{
            // Proceed with login
            String username = txtUser.getText();
            String password = txtPass.getText();
            
            Login emp = new Login(username,password);
            DataIO db = new DataIO();
            if(db.validateLogin(emp)){
                JOptionPane.showMessageDialog(this, "Login Successful");
                jtbMain.setEnabledAt(1,true);
                jtbMain.setSelectedIndex(1);
            }else{
                JOptionPane.showMessageDialog(this, "username/password is incorrect:\n");
            }
            
            // Clear the textfield
            clear();
            
            
        }

    }
    
    private void clear(){
        txtUser.setText("");
        txtUser.setBackground(Color.white);
        txtPass.setText("");
        txtPass.setBackground(Color.white);
    }
}
